# Generated by Django 6.0 on 2026-01-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketTimeline',
        ),
    ]
